Refactored code in compliance with gdscript coding style
Poostaq/Neuroshima-character-creation pull request #3
Opened 2022-04-02 22:42 UTC by Poostaq

Also, deleted some unnecessary file.

2022-04-03 15:19 UTC, Malynna commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +			var traitButtonTraitList = trait_button.get_node("MarginContainer/VBoxContainer/OptionButton")
shoud be: `var trait_button_trait_list`

2022-04-03 15:20 UTC, Malynna commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +	var traitName = trait_button.get_node("MarginContainer/VBoxContainer/TraitNameLabel")
forgot to change

2022-04-03 15:21 UTC, Malynna commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +func create_trait_button(traitTemplate, traitData):
forgot to change

2022-04-03 15:37 UTC, Malynna requested changes
forgot to change some names

2022-04-03 15:37 UTC, Malynna commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +	var traitDescription = trait_button.get_node("MarginContainer/VBoxContainer/TraitDescriptionLabel")
forgot to change

2022-04-03 15:37 UTC, Malynna commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +		bonusAttribute = attribute_selector.selected
forgot to change

2022-04-03 15:37 UTC, Malynna commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +func fill_trait_button_trait_list(traitListElement: OptionButton):
forgot to change

2022-04-03 15:37 UTC, Malynna commented on game/EthnicityPage/EthnicityTrait.gd
> +onready var TraitNameLabel = $MarginContainer/VBoxContainer/TraitNameLabel
forgot to change

2022-04-03 15:37 UTC, Malynna commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +			fill_trait_button_trait_list(traitButtonTraitList)
forgot to change attribute?

2022-04-03 15:37 UTC, Malynna commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +signal ethnicity_chosen(traitElement, currentEthnicity, bonusAttribute)
forgot to change attributes

2022-04-04 09:16 UTC, Poostaq commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +			var traitButtonTraitList = trait_button.get_node("MarginContainer/VBoxContainer/OptionButton")
Fixed

2022-04-04 09:17 UTC, Poostaq commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +	var traitName = trait_button.get_node("MarginContainer/VBoxContainer/TraitNameLabel")
Fixed

2022-04-04 09:17 UTC, Poostaq commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +func create_trait_button(traitTemplate, traitData):
Fixed

2022-04-04 09:17 UTC, Poostaq commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +		bonusAttribute = attribute_selector.selected
Fixed

2022-04-04 09:18 UTC, Poostaq commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +func fill_trait_button_trait_list(traitListElement: OptionButton):
Fixed

2022-04-04 09:18 UTC, Poostaq commented on game/EthnicityPage/EthnicityTrait.gd
> +onready var TraitNameLabel = $MarginContainer/VBoxContainer/TraitNameLabel
Fixed

2022-04-04 09:19 UTC, Poostaq commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +signal ethnicity_chosen(traitElement, currentEthnicity, bonusAttribute)
Fixed

2022-04-04 09:20 UTC, Poostaq commented on game/EthnicityPage/ChooseEthnicityStep.gd
> +			fill_trait_button_trait_list(traitButtonTraitList)
Fixed

2022-04-04 09:36 UTC, Malynna approved these changes

2022-04-04 09:37 UTC, merged